version: "3.8"

networks:
  test:

services:
  server:
    image: "nginx:stable-alpine"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - db
    networks:
      - test
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
      - ./src:/var/www/html/storage/logs
    networks:
      - test
  db:
    build:
      context: .
      dockerfile: dockerfiles/mariaDb.dockerfile
    env_file:
      - ./env/mariadb.env
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - test
    expose:
      - 3306
  myadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80
    networks:
      - test
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - test
  # artisan:
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/php.dockerfile
  #   volumes:
  #     - ./src:/var/www/html
  #   entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
    networks:
      - test
